# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTTP-MobileAgent-Plugin-Extension
version:      0.12022
version_from: lib/HTTP/MobileAgent/Plugin/Extension.pm
installdirs:  site
requires:
    HTTP::MobileAgent:             0.22

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
